language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements_test.txt --use-mirrors
  - pip install -e .
  - pip install coveralls --use-mirrors
  - pip freeze

# command to run tests
script:
    - py.test

after_success:
    - coveralls

