language: python
python: 2.7

env:
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py32-django18
    - TOX_ENV=py33-django18
    - TOX_ENV=py34-django15
    - TOX_ENV=py34-django16
    - TOX_ENV=py34-django18
    # - TOX_ENV=pypy-django14
    - TOX_ENV=pypy-django15
    - TOX_ENV=pypy-django16
    - TOX_ENV=pypy-django18
    - TOX_ENV=pypy3-django15
    - TOX_ENV=pypy3-django16
    - TOX_ENV=pypy3-django18
    - TOX_ENV=coveralls

install:
    pip install tox

script:
    tox -e $TOX_ENV

