language: python
python: 2.7

env:
    - TOX_ENV=coveralls
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django19
    - TOX_ENV=py27-django1a
    - TOX_ENV=py33-django18
    - TOX_ENV=py33-django19
    - TOX_ENV=py33-django1a
    - TOX_ENV=py34-django18
    - TOX_ENV=py34-django19
    - TOX_ENV=py34-django1a
    - TOX_ENV=py35-django18
    - TOX_ENV=py35-django19
    - TOX_ENV=py35-django1a
    - TOX_ENV=pypy-django18
    - TOX_ENV=pypy-django19
    - TOX_ENV=pypy-django1a
    - TOX_ENV=pypy3-django18
    - TOX_ENV=pypy3-django19
    - TOX_ENV=pypy3-django1a

install:
    pip install tox

script:
    tox -e $TOX_ENV

