# Generated by Django 2.1.11 on 2019-08-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The bar name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Egg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The egg name', max_length=50)),
                ('name2', models.CharField(help_text='The egg 2nd name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtraSpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The extra spam name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The foo name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooExtraSpam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra_spam', models.ForeignKey(help_text='The extra spam object', on_delete=django.db.models.deletion.CASCADE, to='autocompletionexample.ExtraSpam')),
                ('foo', models.ForeignKey(help_text='The foo object', on_delete=django.db.models.deletion.CASCADE, to='autocompletionexample.Foo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The spam name', max_length=50)),
                ('foo', models.ManyToManyField(to='autocompletionexample.Foo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='extraspam',
            name='foo',
            field=models.ManyToManyField(through='autocompletionexample.FooExtraSpam', to='autocompletionexample.Foo'),
        ),
        migrations.AddField(
            model_name='egg',
            name='foo',
            field=models.OneToOneField(help_text='The foo object', on_delete=django.db.models.deletion.CASCADE, to='autocompletionexample.Foo'),
        ),
        migrations.AddField(
            model_name='bar',
            name='foo',
            field=models.ForeignKey(help_text='The foo object', on_delete=django.db.models.deletion.CASCADE, to='autocompletionexample.Foo'),
        ),
    ]
