# Generated by Django 2.1.11 on 2019-08-06 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_a', models.CharField(max_length=50)),
                ('name_b', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ErrorName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Impossible to save name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ForeignKeyToSimpleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InlineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManyToManyThrough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManyToManyToDoubleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('double_names', models.ManyToManyField(help_text='Double names help', to='demo.DoubleName', verbose_name='Verbose double names')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManyToManyToError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManyToManyToSimpleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Help text of the name', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ThroughModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('many_to_many_through', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.ManyToManyThrough')),
                ('simple_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.SimpleName')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='manytomanytosimplename',
            name='simple_names',
            field=models.ManyToManyField(help_text='Missing items will be auto-created', to='demo.SimpleName', verbose_name='Verbose simple names'),
        ),
        migrations.AddField(
            model_name='manytomanytoerror',
            name='simple_names',
            field=models.ManyToManyField(help_text='Impossible to save', to='demo.SimpleName', verbose_name='Verbose simple names'),
        ),
        migrations.AddField(
            model_name='manytomanythrough',
            name='simple_names',
            field=models.ManyToManyField(through='demo.ThroughModel', to='demo.SimpleName'),
        ),
        migrations.AddField(
            model_name='inlinemodel',
            name='double_names',
            field=models.ManyToManyField(to='demo.ManyToManyToDoubleName'),
        ),
        migrations.AddField(
            model_name='inlinemodel',
            name='simple_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.SimpleName'),
        ),
        migrations.AddField(
            model_name='inlinemodel',
            name='simple_names',
            field=models.ManyToManyField(to='demo.ManyToManyToSimpleName'),
        ),
        migrations.AddField(
            model_name='foreignkeytosimplename',
            name='simple_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.SimpleName'),
        ),
    ]
